spring:
    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
            WRITE_DATES_AS_TIMESTAMPS: false
        deserialization:
            FAIL_ON_UNKNOWN_PROPERTIES: false
            ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false

application:
    rotter-tomatoes-api-key: qtqep7qydngcc7grk4r4hyd9
    the-movie-db-api-key: 186b266209c2da50f898b7977e2a44dd
    